I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 35, in script
    python:
  File "game/store.rpy", line 37, in <module>
    if client_enter_shop(enter_shop_prob[all_shoppers.index(i)] ):
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 46, in script call
    call screen store_open_screen
  File "game/store.rpy", line 35, in script
    python:
  File "D:\Gamedev\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Gamedev\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/store.rpy", line 37, in <module>
    if client_enter_shop(enter_shop_prob[all_shoppers.index(i)] ):
  File "D:\Gamedev\renpy-7.3.5-sdk\renpy\python.py", line 847, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-7-6.1.7601-SP1
Ren'Py 7.3.5.606
aTry 1.0
Thu Jun 04 17:58:14 2020
